### ISSUE TITLE
Execution hangs when creating a tunnel with username and wrong password

### ISSUE THREAD

**Issue by impero78** [alinex/node-sshtunnel#1]
When creating a tunnel with username/password pair, and the password is wrong the execution seems to stall. Setting the readyTimeout seems not to have any effect either.

(Windows 10 w/node 4.3.0)

**Comment by alinex** [comment]
I will make a test case and check this out. I already now of that problem. It's also a problem with wrong ssh keyfile.

**Comment by alinex** [comment]
Check the new version 1.1.3 which should fix this problem. It was caused by an endless loop in which it tried to connect till it works.

**Comment by impero78** [comment]
Thank you so much, it works now.
On a side note, why dont you provide a package usage example in vanilla js? For beginners like me it would make life easier :) and possibly also attract more downloads

**Comment by alinex** [comment]
Sorry, but this module is very slim but I have others with lots of codes and examples and in my opinion the CoffeeScript source is more readable and better to understand. It also depends on your background, coming from python or ruby it will look more familiar.

The example in js will look like:

``` js
var sshtunnel;
​
sshtunnel = require('alinex-sshtunnel');
​
sshtunnel({
  ssh: {
    host: '65.25.98.25',
    port: 22,
    username: 'root',
    privateKey: require('fs').readFileSync('/home/alex/.ssh/id_rsa'),
    keepaliveInterval: 1000
  },
  tunnel: {
    host: '172.30.0.11',
    port: 80
  }
}, function(err, tunnel) {
  console.log("tunnel opened at " + tunnel.setup.host + ":" + tunnel.setup.port);
  return setTimeout(function() {
    return tunnel.end();
  }, 10000);
});
```

You can always generate it using http://js2.coffee.

**Comment by alinex** [comment]
Maybe in the future I will make the examples in the documentation in both languages. I will think if it is possible to add an JS switch tab while creating the docs under http://alinex.github.io/node-sshtunnel by automatically compiling and adding the alternative code.

As I think about it, it should be possible but only on the site mentioned above, neither in npm view nor in github readme view.

**Comment by alinex** [comment]
It will be possible to add an additional JS Code example withaout always write it two times in documentation. This will go into the next version of my just recently created own code docuemtation tool [codedoc](https://alinex.github.io/node-codedoc). If this is ready I will convert all my documentation one by one.
